GoogleCloudPlatform/datacatalog-connectors

- datacatalog-connectors-commons/setup.py
- datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/datacatalog_facade.py
- Fixes #5
- Added logging for Create Tag Template operation
Added a line to fetch the GRPCIterator before iterating on the new tags.
Create a scenario with an Entry with multiple tags, then change tag values on source system and execute any connector.
Fixes GRPCIterator error on list_tags
> Fix error when upserting and retrieving multiple tags

- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/prepare/base_entry_factory_test.py
Fixed the name of the test case for `_format_id()`.
Renaming the method from to `test_format_display_name_should_normalize_non_compliant_id` to `test_format_id_should_normalize_non_compliant_id`. 
Running the unit tests: `python setup.py test`.
Fix the name of the test case for _format_id().
> Fix the name of the test case for _format_id()

- google-datacatalog-connectors-commons/setup.py
Added enforcement for datacatalog client major version.
Changed setup.py file.
Install the commons library.
The datacatalog client library introduced a breaking change on version 2.0.0, so enforcing the commons library to use version lower than 2.
> FIX set datacatalog client major version

- google-datacatalog-connectors-commons/setup.py
- tools/create-current-version-tags.sh
- tools/release-create-tags.sh
Added script to automatically create tags on release process.
Created the bash script `tools/release-create-tags.sh`.
Run the release tagging step of the release process using the `tools/release-create-tags.sh` script. Afterwards verify the tags were created.
Added script to automatically create tags on release process.
> ADD script to automatically create tags on connectors release process

- .github/workflows/pythonpackage.yml
- google-datacatalog-connectors-commons-test/src/google/datacatalog_connectors/commons_test/utils/utils.py
- google-datacatalog-connectors-commons/setup.py
- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/datacatalog_facade.py
- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/prepare/base_entry_relationship_mapper.py
- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/prepare/base_tag_factory.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/datacatalog_facade_test.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/ingest/datacatalog_metadata_ingestor_test.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/prepare/base_entry_relationship_mapper_test.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/prepare/base_tag_factory_test.py
Updated the code to make compatible with the Data Catalog client library v2.0.0
Followed the instructions from the [2.0.0 Migration Guide](https://github.com/googleapis/python-datacatalog/blob/master/UPGRADING.md) and other changes not covered in that guide.
Run the unit tests.
Upgrade datacatalog client library version to 2.0.0
Closes #17
> Upgrade datacatalog client library version to 2.0.0

- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/prepare/base_tag_factory.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/prepare/base_tag_factory_test.py
FIX Tag field logic when double value was zero
changed the way the double value is tested.
use the `_set_double_field` method with zero value
FIX Tag field logic when double value was zero
> FIX Tag field logic when double value was zero

- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/datacatalog_facade.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/datacatalog_facade_test.py
Fixed the `search_catalog()` arguments and simplified all other datacatalog client method calls.
Removed the `request` argument from all method calls e restored the previous notation.
Run the unit tests.
Fixed and simplified datacatalog client method calls
> Fix and simplify DC client method calls

- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/datacatalog_facade.py
added logic to handle none timestamp fields.
added logic to handle none timestamp fields.
Run a RDBMS connector which does not have the timestamp fields.
FIX `__entry_was_updated` method to handle none timestamp fields
> FIX __entry_was_updated  method to handle none timestamp fields

- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/prepare/__init__.py
- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/prepare/base_tag_template_factory.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/prepare/base_entry_factory_test.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/prepare/base_tag_factory_test.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/prepare/base_tag_template_factory_test.py
Created a parent class to share helper code with all Tag Template factories.
Created the `BaseTagTemplateFactory` class in `google.datacatalog_connectors.commons.prepare`.
Run the unit tests.
Added the BaseTagTemplateFactory class
> Create the BaseTagTemplateFactory class

- .github/workflows/pythonpackage.yml
- google-datacatalog-connectors-commons-test/setup.py
- google-datacatalog-connectors-commons/setup.py
Fixed version on `setup.py` so it's using a version compatible with python3.8.
Fixed version on `setup.py` so it's using a version compatible with python3.8.
Run the connector commons on a python3.7 or python3.8  env
UPDATE pandas version to be compatible with python3.7 and python3.8
> UPDATE pandas version to be compatible with python3.7 and python3.8

- google-datacatalog-connectors-commons/setup.py
- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/datacatalog_facade.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/datacatalog_facade_test.py
Changed tag column comparison to ignore case.
Changed tag column comparison to ignore case.
Run a SQL connector which returns uppercased column names.
Data Catalog entry columns names are case insensitive, so we need to ignore case.
> Fix scenario when columns are created with uppercased names

- google-datacatalog-connectors-commons/setup.py
Fixed the DC library version to be lower than 3.0.0 on `setup.py`
Fixed the DC library version to be lower than 3.0.0 on `setup.py`
Run any connector tests.
Google Data Catalog library has some breaking changes to the connectors on the version 3.0.0, this is breaking the hive connector: https://github.com/GoogleCloudPlatform/datacatalog-connectors-hive/issues/20 and most likely the other connectors.
> FIX set version of google datacatalog library to lower than v3.0.0

- google-datacatalog-connectors-commons/setup.py
- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/prepare/base_entry_relationship_mapper.py
Fixed a bug in `google-datacatalog-connectors-commons` that was preventing dependent connectors to fulfill relationship fields in all Tags when a given Entry had more than one Tag related to the same "upstream" asset.
Changed `BaseEntryRelationshipMapper._map_related_entry()` to handle a list of Tags for any related asset Id, instead of handling a single Tag per asset Id.
Run the unit tests (coverage remains the same) and, preferably, any connector to make sure all Tag relationship fields are properly fulfilled.
Fulfill multiple Tag relationships
> Fulfill multiple Tag relationships

- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/datacatalog_facade.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/datacatalog_facade_test.py
Added an `except` clause to handle the `FailedPrecondition` exception. If this happens the entry is not ingested, a warning is logged and the connector goes to the next entry.
Added an `except` clause to handle the `FailedPrecondition` exception.
1. Run a connector that ingests a large number of entries 10.000+
2. Clean up the ingested entries
3. Run the connector again in a short time span, like 1 hour from the first run.
This scenario should not break the connector now with this change.
Fixes #37. 
There is also an open issue related to this: https://issuetracker.google.com/issues/170052119. So this PR proposes to ignore the error and skip the entry ingestion. As described in the open issue …
> Add code to handle pre condition error on create_entry logic

- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/prepare/base_entry_factory.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/prepare/base_entry_factory_test.py
Added a new method to the `base_entry_factory.py` class to enable formatting entry id with hashing.
Uses the `hashlib` lib.
Run hive connector in a hive server with tables that contain more than 64 chars.
Hive table names can have 256 characters, so formatting the id with the existent strategy, by cutting to 64 chars (which is  the entry id limit) is not safe. In an environment with thousands of tables it's easy to have a name collision if we cut it that way.
This new strategy cuts the id and adds a hash created from the full id, that way we avoid collisions if the table name changes only in the final characters. The method receives the `length_to_hash` so the connector can hash it up to 64 …
> ADD new method to format entry id with hashing

- google-datacatalog-connectors-commons/setup.py
- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/prepare/base_entry_factory.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/prepare/base_entry_factory_test.py
Added a new argument to `_format_id_with_hashing` to pass the regex pattern.
Added a new argument to `_format_id_with_hashing` to pass the regex pattern.
Use the `_format_id_with_hashing` and pass the regex pattern.
Some connectors might use a different pattern to format the id, so this should be open for extension. Having an argument in the method enable this, and let each connector take the decision.
In order to not impact existent connectors, we use a default value.
> Add a new argument to _format_id_with_hashing to pass the regex pattern

- google-datacatalog-connectors-commons/setup.py
- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/datacatalog_facade.py
- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/ingest/datacatalog_metadata_ingestor.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/datacatalog_facade_test.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/ingest/datacatalog_metadata_ingestor_test.py
Improved exception handling of `upsert_entries` method to skip `upsert_tags` logic.
Moved the exception handling to the `__ingest_entries` logic.
Run a connector where any entry is in the `exceptions.FailedPrecondition` state. (usually this happens when you create entries in the same entry group multiple times or with a large amount of entries 5k+ 10k+). The entry and the create tags logic should be skipped.
When a `exceptions.FailedPrecondition` was raised on `upsert_entries` the exception was caught and not raised, so the ingest_entries logic would attempt to create the entry tags.
The connector should skip the entry and also the tags creation in this scenario, so the exception handling needs …
> Improve exception handling of upsert_entries to skip upsert_tags logic

- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/prepare/base_entry_factory.py
Added the `strip()` logic to the `__normalize_string` method.  
We already have a `strip()` call to the `__normalize_ascii_chars`, as it can be seen on the `__normalize_string` method:
```
@classmethod
def __normalize_string(cls, regex_pattern, source_string):
formatted_str = re.sub(
regex_pattern, '_',
cls.__normalize_ascii_chars(source_string.strip()))
return formatted_str.strip()
```
But running the looker connector I was able to generate display names that contain spaces at the end of the string. So this change adds a `strip()` call to the `formatted_str` return to make sure the formatted string won't have this extra space.
Run the looker connector as it can be seen on #46. The error should not happen with this change, and entries should be …
> Added trim logic to commons normalize string method.

- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/utils/__init__.py
- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/utils/region_tag_helper.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/utils/region_tag_helper_test.py
Created a helper class to extract the content of region tags. The name "region  tags" is inspired on the code samples region tags.
Used a regex expression to extract the content group.
Run the new unit tests with this PR.
Creates a common class needed to implement the feature request: https://github.com/GoogleCloudPlatform/datacatalog-connectors-rdbms/issues/63
> ADD helper class to extract region tags content

- google-datacatalog-connectors-commons/.coveragerc
- google-datacatalog-connectors-commons/src/google/datacatalog_connectors/commons/prepare/base_tag_template_factory.py
- google-datacatalog-connectors-commons/tests/google/datacatalog_connectors/commons/prepare/base_tag_template_factory_test.py
Added code to handle the optional `is_required` and `order` Tag Template Field attributes.
Added new optional input args to the `prepare.BaseTagTemplateFactory` public methods and used them to set the above-mentioned field attributes.
Run the unit tests and, preferably, some dependent connector in an integrated environment to make sure there are no breaking changes.
Added code to handle the optional `is_required` and `order` Tag Template Field attributes.
Closes #32.
> Add optional Tag Template Field attributes
